export const metadata = {
  title: 'Next.js',
  description: 'Not Generated by Next.js',
};
 
export default function RootLayout({ children }) {
  return (
    <html>
        <head>
            <title>RoR 2 Item Generator</title>
            <link rel="stylesheet" href="css/styles.css" />
        </head>
      <body>
        <div id = "content">{children}</div>
        </body>
    </html>
  );
}